#!/usr/bin/env bun
/**
 * Generates src/version.ts with build-time version, channel, and commit info.
 * Run before bun compile to embed version identity in the binary.
 *
 * Usage:
 *   bun run cli/scripts/gen-version.ts                    # stable, version from package.json
 *   bun run cli/scripts/gen-version.ts --channel alpha    # alpha channel
 *   bun run cli/scripts/gen-version.ts --tag alpha-20260318-075857-8b1c13d
 *
 * When --tag is provided, it becomes the version string for alpha builds.
 * When omitted, version comes from package.json.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { join } from "node:path";

const scriptDir = import.meta.dir;
const cliDir = join(scriptDir, "..");
const outFile = join(cliDir, "src/version.ts");

// Parse args
const args = process.argv.slice(2);
function getArg(name: string): string | undefined {
  const idx = args.indexOf(`--${name}`);
  return idx >= 0 && idx + 1 < args.length ? args[idx + 1] : undefined;
}

const channel = getArg("channel") || "stable";
const tag = getArg("tag");

// Read package.json version
const pkg = JSON.parse(readFileSync(join(cliDir, "package.json"), "utf-8"));
const semver: string = pkg.version || "0.0.0";

// For alpha, version is the tag (e.g. "alpha-20260318-075857-8b1c13d")
// For stable, version is the semver from package.json (e.g. "0.1.0")
const version = channel === "alpha" && tag ? tag : semver;

// Git commit (short hash)
let commit = "unknown";
try {
  commit = execSync("git rev-parse --short HEAD", { encoding: "utf-8", cwd: join(cliDir, "..") }).trim();
} catch {
  // Not in a git repo or git not available
}

const buildTime = new Date().toISOString();

const output = `// Auto-generated by scripts/gen-version.ts — do not edit
// Build-time version identity for the compiled binary

export const VERSION = ${JSON.stringify(version)};
export const SEMVER = ${JSON.stringify(semver)};
export const CHANNEL: "stable" | "alpha" = ${JSON.stringify(channel)};
export const COMMIT = ${JSON.stringify(commit)};
export const BUILD_TIME = ${JSON.stringify(buildTime)};
`;

writeFileSync(outFile, output);
console.log(`Generated ${outFile}: ${channel} ${version} (${commit})`);
